### ISSUE TITLE
Could you elaborate what exactly this returns?

### ISSUE THREAD

**Issue by ngacho** [ngacho/pacman-contest#3]
https://github.com/ngacho/pacman-contest/blob/ee7e7085900ae4a190b35790afdf60c7a2b69d2b/myTeam.py#L111

**Comment by ahmed-k-aly** [comment]
this returns the state the agent passed in is at. Basically a string that says whether it's a ghost or pacman. I was using it before we knew we could use the agentState class. I'll remove it to use the latter now
