### ISSUE TITLE
I don't see this checking if the enemy is near us, it just straight up goes for particle filtering. I think I have a method that does both, let me know if I should update it

### ISSUE THREAD

**Issue by ngacho** [ngacho/pacman-contest#4]
https://github.com/ngacho/pacman-contest/blob/ee7e7085900ae4a190b35790afdf60c7a2b69d2b/myTeam.py#L135

**Comment by ahmed-k-aly** [comment]
You don't need a method that does both. In my particle filtering class, I stop inferring if the enemy is within our range, so if they're less than 5 blocks away, there is only one position in the counter, so we're 100% certain where the agent is.
