### ISSUE TITLE
Why are we getting distance to bases when we have a method taking us to home base.

### ISSUE THREAD

**Issue by ngacho** [ngacho/pacman-contest#5]
https://github.com/ngacho/pacman-contest/blob/ee7e7085900ae4a190b35790afdf60c7a2b69d2b/myTeam.py#L166

**Comment by ahmed-k-aly** [comment]
distance to base is used as a feature in my q agent as the further he gets away from base, the worse it is for him. Go home returns an action, which doesn't help in learning
